version: "2.4"
services:
  dev-db:
    container_name: "dev-db"
    image: "postgres:15"
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=awO4Bqkqna
      - POSTGRES_DB=nest-docker
  test-db:
    container_name: "test-db"
    image: "postgres:15"
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=awO4Bqkqna
      - POSTGRES_DB=nest-docker
